[package]
name = "vicinal"
description = "Processor-local worker pool that schedules tasks in the vicinity of the caller"
publish = true
version = "0.1.3"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = []

[dependencies]
event-listener = { workspace = true }
events_once = { workspace = true }
fast_time = { workspace = true }
infinity_pool = { workspace = true }
many_cpus = { workspace = true }
new_zealand = { workspace = true }
nm = { workspace = true }
parking_lot = { workspace = true }
parking_lot_core = "0.9"
pin-project = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
all_the_time = { path = "../all_the_time" }
alloc_tracker = { path = "../alloc_tracker" }
criterion = { workspace = true }
futures = { workspace = true }
many_cpus.workspace = true
mutants = { workspace = true }
static_assertions = { workspace = true }
testing = { path = "../testing" }
threadpool = "1.8.1"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true

[[bench]]
name = "vicinal_benches"
harness = false
