[package]
name = "ui_tests"
version = "0.0.0-never"
publish = false
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dev-dependencies]
infinity_pool = { workspace = true }
new_zealand = { workspace = true }
trybuild = { workspace = true }

[package.metadata.cargo-udeps.ignore]
# udeps fails to "look through" trybuild tests, so we need to exclude all our dependencies here.
development = ["infinity_pool", "new_zealand"]
