[package]
name = "events_once"
description = "Efficient oneshot events (channels) with support for single-threaded events, object embedding, event pools and event lakes"
publish = true
version = "0.5.11"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = []

[dependencies]
hash_hasher = { workspace = true }
infinity_pool = { workspace = true }
parking_lot = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
mutants = { workspace = true }
oneshot = { workspace = true }
pin-project = { workspace = true }
spin_on = { workspace = true }
static_assertions = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread", "time"] }

[lints]
workspace = true

[[bench]]
name = "ev_once_local"
harness = false

[[bench]]
name = "ev_once_sync"
harness = false

[[bench]]
name = "ev_once_vs_3p"
harness = false
